services:
  journiv:
    image: swalabtech/journiv-app:latest
    container_name: journiv
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-here # Replace with a strong secret key
      - DOMAIN_NAME=192.168.1.1 # Your server IP or domain
    volumes:
      - journiv_data:/data
    restart: unless-stopped

volumes:
  journiv_data:
